Question 1: Create a NumPy array with 5 elements initialized with zeros.

In [ ]:
import numpy as np

In [ ]:
array = np.zeros(5)
print(array)

[0. 0. 0. 0. 0.]


Question 2: Create a NumPy array with 3 rows and 4 columns initialized with ones.


In [ ]:
array = np.ones((3, 4))
print(array)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Question 3: Create a 1D NumPy array containing numbers from 1 to 10.

In [ ]:
one_d =np.array([1,2,3,4,5,6,7,8,9,10])
print(one_d)

[ 1  2  3  4  5  6  7  8  9 10]


Question 4: Create a 2D NumPy array with dimensions 3x3 containing numbers from 1 to 9.

In [ ]:
two_d = np.arange(1, 10).reshape(3, 3)
print(two_d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Question 5: Create a 3D NumPy array with dimensions 2x3x4 containing random integers between 0 and 9.

In [ ]:
array = np.random.randint(0, 10, size=(2, 3, 4))

print(array)

[[[5 5 0 3]
  [2 3 4 8]
  [2 3 1 1]]

 [[8 4 0 0]
  [7 4 6 7]
  [0 4 8 4]]]


Question 6: Create a NumPy array from a list containing elements [1, 2, 3, 4, 5].


In [ ]:
array = np.array([1, 2, 3, 4, 5])
print(array)

[1 2 3 4 5]


Question 7: Convert a tuple (6, 7, 8, 9, 10) into a NumPy array.

In [ ]:
a=(6,7,8,9,10)
b=np.array(a)
print(b)

[ 6  7  8  9 10]


Question 8: Create a NumPy array with shape (4, 2) containing numbers from 0 to 7.


In [ ]:
array = np.arange(8).reshape(4, 2)
print(array)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


Question 9: Create a 3D NumPy array with shape (2, 3, 4) initialized with zeros.


In [ ]:
array = np.zeros((2, 3, 4))
print(array)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


Question 10: Create a 2D NumPy array with shape (3, 3) containing random floating-point numbers between 0 and 1.


In [ ]:
array = np.random.rand(3, 3)
print(array)

[[0.87693603 0.81778806 0.68553621]
 [0.7607883  0.3078153  0.80833298]
 [0.49300924 0.30582528 0.84850514]]


Question 11: Create a NumPy array with shape (5,) containing numbers from 10 to 50, incrementing by 5.


In [ ]:
array = np.arange(10, 50, 5)
print(array)

[10 15 20 25 30 35 40 45]


Question 12: Create a NumPy array with shape (2, 5) containing numbers from -2 to 7.


In [ ]:
array = np.arange(-2, 8).reshape(2, 5)
print(array)

[[-2 -1  0  1  2]
 [ 3  4  5  6  7]]


Question 13: Create a 1D NumPy array with shape (10,) containing numbers from 100 to 109, and change its data type to float.


In [ ]:
array = np.arange(100, 110)
print(array)
array1 = array.astype(float)
print(array1)

[100 101 102 103 104 105 106 107 108 109]
[100. 101. 102. 103. 104. 105. 106. 107. 108. 109.]


Question 14: Create a 2D NumPy array with shape (3, 4) initialized with ones, and then change its data type to int.


In [ ]:
array = np.ones((3, 4))
print(array)
array1 = array.astype(int)

print(array1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


Question 15: Create a 3D NumPy array with shape (2, 2, 3) initialized with specified numbers [[1, 2, 3], [4, 5, 6]], and [[7, 8, 9], [10, 11, 12]].

In [ ]:
array = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])
print(array)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
